/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.de_alone.dokkang;

public class DokkangServerApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new DokkangServerApplication().getGreeting());
    }
}
