/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.de_alone.dokkang;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        DokkangServerApplication classUnderTest = new DokkangServerApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        assertNotNull(null);
    }
}
